/* -------------------------------------------------------------------------
** QueryParameters.hpp
**
** The QueryParameters class is the parent class that the query parameters
** classes generated by the editor inherit from. The QueryContainer will
** create and delete it.
**
** Author: Mike Sansone
** ------------------------------------------------------------------------- */

#ifndef _QUERYPARAMETERS_HPP_
#define _QUERYPARAMETERS_HPP_

#if defined(FIREMELON_EXPORTS)
#   define FIREMELONAPI   __declspec(dllexport)
#else
#   define FIREMELONAPI   __declspec(dllimport)
#endif  // FIREMELON_EXPORTS

namespace firemelon
{
	class FIREMELONAPI QueryParameters
	{
	public:

		QueryParameters();
		virtual ~QueryParameters();
	
	private:

	};
}

#endif // _QUERYPARAMETERS_HPP_