/* -------------------------------------------------------------------------
** QueryResultFactory.hpp
**
** The QueryResultFactory class is the parent class of the query result
** factory class that is generated by the editor. It is used internally by the 
** query container to create the user defined query result objects.
**
** Author: Mike Sansone
** ------------------------------------------------------------------------- */

#ifndef _QUERYRESULTFACTORY_HPP_
#define _QUERYRESULTFACTORY_HPP_

#if defined(FIREMELON_EXPORTS)
#   define FIREMELONAPI   __declspec(dllexport)
#else
#   define FIREMELONAPI   __declspec(dllimport)
#endif  // FIREMELON_EXPORTS

#include "QueryResult.hpp"
#include "BaseIds.hpp"

namespace firemelon
{
	class FIREMELONAPI QueryResultFactory
	{
	public:
		QueryResultFactory();
		virtual ~QueryResultFactory();
		
		virtual QueryResult* createQueryResult(QueryId queryType);

		QueryResult* createQueryResultBase(QueryId queryType);

	private:
	};
}

#endif // _QUERYRESULTFACTORY_HPP_