/* -------------------------------------------------------------------------
** QueryFactory.hpp
**
** The QueryFactory class is the parent class of the query factory class that 
** is generated by the editor. It is used internally by the query container to 
** create the user defined query objects.
**
** Author: Mike Sansone
** ------------------------------------------------------------------------- */

#ifndef _QUERYFACTORY_HPP_
#define _QUERYFACTORY_HPP_

#if defined(FIREMELON_EXPORTS)
#   define FIREMELONAPI   __declspec(dllexport)
#else
#   define FIREMELONAPI   __declspec(dllimport)
#endif  // FIREMELON_EXPORTS

#include "Query.hpp"

namespace firemelon
{
	class FIREMELONAPI QueryFactory
	{
	public:
		QueryFactory();
		virtual ~QueryFactory();
		
		virtual boost::shared_ptr<Query>	createQuery(QueryId queryType);
		
		boost::shared_ptr<Query>			createQueryBase(QueryId queryType);

	private:
	};
}

#endif // _QUERYFACTORY_HPP_